//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：FamilyMembers.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:12
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class FamilyMembers
	{
		#region Data

		/// <summary>
		/// 编号
		/// </summary>
		private string _familyMembersId;
		
		/// <summary>
		/// 员工编号
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 名称
		/// </summary>
		private string _familyMembersName;
		
		/// <summary>
		/// 身份证
		/// </summary>
		private string _personId;
		
		/// <summary>
		/// 关系
		/// </summary>
		private string _relation;
		
		/// <summary>
		/// 生日
		/// </summary>
		private DateTime? _birthday;
		
		/// <summary>
		/// 员工
		/// </summary>
		private Employee employee;

        private decimal? _laobaoMoney;

        private decimal? _jianbaoMoney;

		#endregion
		
		#region Properties
		
		/// <summary>
		/// 编号
		/// </summary>
		public string FamilyMembersId
		{
			get 
			{
				return this._familyMembersId;
			}
			set 
			{
				this._familyMembersId = value;
			}
		}

		/// <summary>
		/// 员工编号
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 名称
		/// </summary>
		public string FamilyMembersName
		{
			get 
			{
				return this._familyMembersName;
			}
			set 
			{
				this._familyMembersName = value;
			}
		}

		/// <summary>
		/// 身份证
		/// </summary>
		public string PersonId
		{
			get 
			{
				return this._personId;
			}
			set 
			{
				this._personId = value;
			}
		}

		/// <summary>
		/// 关系
		/// </summary>
		public string Relation
		{
			get 
			{
				return this._relation;
			}
			set 
			{
				this._relation = value;
			}
		}

		/// <summary>
		/// 生日
		/// </summary>
		public DateTime? Birthday
		{
			get 
			{
				return this._birthday;
			}
			set 
			{
				this._birthday = value;
			}
		}
	
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this.employee;
			}
			set
			{
				this.employee = value;
			}
			
		}

        /// <summary>
        /// 勞保負擔金額
        /// </summary>
        public decimal? LaobaoMoney
        {
            get { return _laobaoMoney; }
            set { _laobaoMoney = value; }
        }
        
        /// <summary>
        /// 健保負擔金額
        /// </summary>
        public decimal? JianbaoMoney
        {
            get { return _jianbaoMoney; }
            set { _jianbaoMoney = value; }
        }		 

		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PROPERTY_FAMILYMEMBERSID = "FamilyMembersId";
		
		/// <summary>
		/// 员工编号
		/// </summary>
		public readonly static string PROPERTY_EMPLOYEEID = "EmployeeId";
		
		/// <summary>
		/// 名称
		/// </summary>
		public readonly static string PROPERTY_FAMILYMEMBERSNAME = "FamilyMembersName";
		
		/// <summary>
		/// 身份证
		/// </summary>
		public readonly static string PROPERTY_PERSONID = "PersonId";
		
		/// <summary>
		/// 关系
		/// </summary>
		public readonly static string PROPERTY_RELATION = "Relation";
		
		/// <summary>
		/// 生日
		/// </summary>
		public readonly static string PROPERTY_BIRTHDAY = "Birthday";

        public readonly static string PRO_LaobaoMoney = "LaobaoMoney";

        public readonly static string PRO_JianbaoMoney = "JianbaoMoney";

		#endregion
	}
}
